version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7-rc-node

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Run tests.
          command: |
            pip install tox
            tox
